Repository kubic-project/velum, pull requests merged in 2018-09, with the labels that each got.

#631 [3.0] PublicCloud#remove: Not yet implemented
  app/assets/javascripts/dashboard/dashboard.js
  app/controllers/minions_controller.rb
  app/models/minion.rb
  spec/controllers/minions_controller_spec.rb
  spec/features/node_removal_feature_spec.rb
Labels: no-bugzilla-ref, release-3.0-backport

#588 [3.0] Add a feature spec for building cluster in Azure
  spec/features/bootstrap_in_azure_feature_spec.rb
Labels: no-bugzilla-ref, release-3.0-backport

#628 [3.0] Fix pillar issue in public cloud
  app/models/cloud_cluster.rb
  lib/velum/salt.rb
  spec/vcr_cassettes/salt/cloud_profile.yml
  spec/vcr_cassettes/salt/login_500.yml
  spec/vcr_cassettes/salt/refresh_pillar.yml
Labels: no-bugzilla-ref, release-3.0-backport

#646 specs: fixed TempFile usage for file fixtures
  spec/controllers/settings/dex_connector_ldaps_controller_spec.rb
  spec/controllers/settings/registries_controller_spec.rb
  spec/controllers/settings/registry_mirrors_controller_spec.rb
  spec/controllers/settings/system_certificates_controller_spec.rb
  spec/controllers/setup_controller_spec.rb
  spec/features/settings/dex_connector_ldap_feature_spec.rb
  spec/features/settings/mirrors_feature_spec.rb
  spec/features/settings/registries_feature_spec.rb
  spec/rails_helper.rb
Labels: no-bugzilla-ref

#639 Allow to configure Kubernetes log level globally.
  app/models/pillar.rb
Labels: release-3.0-candidate

#656 ldap (specs): minor improvements using capybara convetions
  app/views/settings/dex_connector_ldaps/_form.html.slim
  spec/features/settings/dex_connector_ldap_feature_spec.rb
Labels: no-bugzilla-ref

#657 Backport of LDAP external auth feature
  app/assets/javascripts/application.js
  app/assets/javascripts/settings/index.js
  app/assets/javascripts/settings/ldap-conn-test.js
  app/assets/stylesheets/pages/settings.scss
  app/controllers/internal_api/v1/pillars_controller.rb
  app/controllers/settings/base_certificate_controller.rb
  app/controllers/settings/dex_connector_ldaps_controller.rb
  app/controllers/settings/ldap_test_controller.rb
  app/controllers/settings/registries_controller.rb
  app/controllers/settings/registry_mirrors_controller.rb
  app/controllers/settings/system_certificates_controller.rb
  app/controllers/setup_controller.rb
  app/helpers/settings_helper.rb
  app/models/certificate.rb
  app/models/dex_connector_ldap.rb
  app/models/system_certificate.rb
  app/views/settings/_sidebar.html.slim
  app/views/settings/dex_connector_ldaps/_form.html.slim
  app/views/settings/dex_connector_ldaps/edit.html.slim
  app/views/settings/dex_connector_ldaps/index.html.slim
  app/views/settings/dex_connector_ldaps/new.html.slim
  app/views/settings/dex_connector_ldaps/show.html.slim
  app/views/settings/registries/_form.html.slim
  app/views/settings/registry_mirrors/_form.html.slim
  app/views/settings/system_certificates/_fields.html.slim
  app/views/settings/system_certificates/_form.html.slim
  config/initializers/filter_parameter_logging.rb
  config/ldap_mock.yml
  config/routes.rb
  db/migrate/20181708070234_create_dex_connectors_ldap.rb
  db/migrate/20181715075510_alter_dex_defaults.rb
  db/schema.rb
  lib/velum/dex/ldap.rb
  lib/velum/ldap_mock.rb
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
  spec/controllers/settings/dex_connector_ldaps_controller_spec.rb
  spec/controllers/settings/ldap_test_controller_spec.rb
  spec/controllers/settings/registries_controller_spec.rb
  spec/controllers/settings/registry_mirrors_controller_spec.rb
  spec/controllers/settings/system_certificates_controller_spec.rb
  spec/controllers/setup_controller_spec.rb
  spec/factories/dex_connectors_ldap_factory.rb
  spec/features/settings/dex_connector_ldap_feature_spec.rb
  spec/features/settings/mirrors_feature_spec.rb
  spec/features/settings/registries_feature_spec.rb
  spec/models/dex_connector_ldap_spec.rb
  spec/rails_helper.rb
Labels: no-bugzilla-ref, release-3.0-backport

#658 specs: fixed minor mismatching expectation
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
Labels: no-bugzilla-ref, release-3.0-backport

#641 use online status during update for update status
  app/assets/javascripts/dashboard/dashboard.js
Labels: release-3.0-candidate

#647 FIX bsc#1099985 removes unassigned nodes and add a reject node link
  .gitignore
  README.md
  app/assets/javascripts/dashboard/dashboard.js
  app/controllers/salt_controller.rb
  app/models/minion.rb
  app/models/salt_event.rb
  app/models/salt_handler/auth_event.rb
  app/views/dashboard/unassigned_nodes.html.slim
  app/views/setup/discovery.html.slim
  config/routes.rb
  lib/velum/salt.rb
  spec/features/bootstrap_cluster_feature_spec.rb
  spec/features/dashboard_feature_spec.rb
  spec/lib/velum/salt_spec.rb
  spec/models/minion_spec.rb
  spec/models/salt_event_spec.rb
  spec/models/salt_handler/auth_event_spec.rb
  spec/support/utils.rb
  spec/vcr_cassettes/salt/reject_minion.yml
  spec/vcr_cassettes/salt/remove_minion.yml
Labels: bug

#668 [3.0] [bsc#1109320] Fix external auth group mapping for group attr name
  lib/velum/dex/ldap.rb
Labels: P2 bug, bug, release-3.0-backport

#660 [bsc#1108740] dont allow updating admin again when cluster update failed
  app/assets/javascripts/dashboard/dashboard.js
Labels: bug

#662 [3.0] update sprockets to fix cve-2018-3760 cve#2018-3760
  Gemfile.lock
Labels: bug, no-bugzilla-ref, release-3.0-backport
