Repository kubic-project/velum, pull requests merged in 2018-10, with the labels that each got.

#651 [BSC#1107545] Migrate subnet pillar name v2.1 -> v3
  app/models/pillar.rb
  db/migrate/20181715075511_rename_cloud_subnet_pillar.rb
  db/schema.rb
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
Labels: no-bugzilla-ref, release-3.0-backport

#649 [BSC#1107495] Update bootstrap-slider
  vendor/assets/javascript/bootstrap-slider.min.js
  vendor/assets/stylesheets/bootstrap-slider.min.css
Labels: no-bugzilla-ref, release-3.0-backport

#642 [3.0] when rebooting admin, set tx_update_reboot_needed to false
  app/controllers/updates_controller.rb
Labels: P2 bug, bug, release-3.0-backport

#670 [3.0][bsc#1108740] dont allow updating admin again when cluster update failed
  app/assets/javascripts/dashboard/dashboard.js
Labels: P2 bug, release-3.0-backport

#659 [3.0][bsc#1108679] use online status during update for update status
  app/assets/javascripts/dashboard/dashboard.js
Labels: release-3.0-backport

#605 [3.0] ui: renamed new nodes -> unassigned nodes
  app/assets/stylesheets/pages/nodes_list.scss
  app/views/dashboard/index.html.slim
Labels: release-3.0-backport

#592 [3.0] Fix bsc#1072242: Use keyboard layout from admin installation.
  app/controllers/dashboard_controller.rb
  app/views/dashboard/autoyast.xml.erb
  lib/velum/autoyast_values.rb
  spec/controllers/dashboard_controller_spec.rb
Labels: release-3.0-backport

#615 [3.0] Update the minion hostname in a regular basis, based on the grain information.
  app/models/minion.rb
Labels: release-3.0-backport

#640 [3.0] Allow to configure Kubernetes log level globally.
  app/models/pillar.rb
Labels: release-3.0-backport

#625 Fix smally typo
  app/views/oidc/done.html.slim
Labels: release-3.0-backport

#671 [3.0] FIX bsc#1099985 removes unassigned nodes and add a reject node link
  .gitignore
  README.md
  app/assets/javascripts/dashboard/dashboard.js
  app/controllers/salt_controller.rb
  app/models/minion.rb
  app/models/salt_event.rb
  app/models/salt_handler/auth_event.rb
  app/views/dashboard/unassigned_nodes.html.slim
  app/views/setup/discovery.html.slim
  config/routes.rb
  lib/velum/salt.rb
  spec/features/bootstrap_cluster_feature_spec.rb
  spec/features/dashboard_feature_spec.rb
  spec/lib/velum/salt_spec.rb
  spec/models/minion_spec.rb
  spec/models/salt_event_spec.rb
  spec/models/salt_handler/auth_event_spec.rb
  spec/support/utils.rb
  spec/vcr_cassettes/salt/reject_minion.yml
  spec/vcr_cassettes/salt/remove_minion.yml
Labels: release-3.0-backport

#693 followup fix for bsc#1108740
  app/assets/javascripts/dashboard/dashboard.js
Labels: P2 bug, release-3.0-candidate
