Repository kubic-project/velum, pull requests merged in 2018-05, with the labels that each got.

#508 [2.1] Fixed misleading text about nodes selection
  app/views/setup/discovery.html.slim
Labels: release-2.1-backport

#511 [3.0] Fixed misleading text about nodes selection
  app/views/setup/discovery.html.slim
Labels: release-3.0-backport

#512 [3.0] Use `update_columns` to update minion attributes with the minion reconciler
  app/models/minion.rb
  spec/features/node_force_removal_feature_spec.rb
Labels: release-3.0-backport

#513 [3.0] Make the `bin/init` process only do initialization operations
  bin/init
  bin/run
Labels: release-3.0-backport

#502 Salt-cloud feedback
  app/assets/javascripts/dashboard/dashboard.js
  app/controllers/concerns/discovery.rb
  app/controllers/setup_controller.rb
  app/models/cloud_cluster.rb
  app/models/salt_event.rb
  app/models/salt_handler/cloud_bootstrap.rb
  app/models/salt_job.rb
  app/views/setup/discovery.html.slim
  db/migrate/20180427014552_create_salt_jobs.rb
  db/schema.rb
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/controllers/setup_controller_spec.rb
  spec/factories/salt_job_factory.rb
  spec/features/bootstrap_cluster_feature_spec.rb
  spec/models/cloud_cluster_spec.rb
  spec/models/salt_handler/cloud_bootstrap_spec.rb
  spec/models/salt_job_spec.rb
  spec/vcr_cassettes/salt/cloud_profile.yml
  spec/vcr_cassettes/salt/login_500.yml
Labels: release-2.1-backport, release-3.0-backport

#517 Salt cloud feedback - r2.1
  app/assets/javascripts/dashboard/dashboard.js
  app/controllers/concerns/discovery.rb
  app/controllers/setup_controller.rb
  app/models/cloud_cluster.rb
  app/models/salt_event.rb
  app/models/salt_handler/cloud_bootstrap.rb
  app/models/salt_job.rb
  app/views/setup/discovery.html.slim
  db/migrate/20180427014552_create_salt_jobs.rb
  db/schema.rb
  packaging/suse/patches/1_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/controllers/setup_controller_spec.rb
  spec/factories/salt_job_factory.rb
  spec/features/bootstrap_cluster_feature_spec.rb
  spec/models/cloud_cluster_spec.rb
  spec/models/salt_handler/cloud_bootstrap_spec.rb
  spec/models/salt_job_spec.rb
  spec/vcr_cassettes/salt/cloud_profile.yml
  spec/vcr_cassettes/salt/login_500.yml
Labels: release-2.1-backport

#440 [2.1] Add fallback link to fetch kubeconfig if redirect fails
  app/controllers/oidc_controller.rb
  app/views/oidc/done.html.slim
  app/views/oidc/kubeconfig.erb
Labels: release-2.1-backport

#516 Salt cloud feedback - r3.0
  app/assets/javascripts/dashboard/dashboard.js
  app/controllers/concerns/discovery.rb
  app/controllers/setup_controller.rb
  app/models/cloud_cluster.rb
  app/models/salt_event.rb
  app/models/salt_handler/cloud_bootstrap.rb
  app/models/salt_job.rb
  app/views/setup/discovery.html.slim
  db/migrate/20180427014552_create_salt_jobs.rb
  db/schema.rb
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/controllers/setup_controller_spec.rb
  spec/factories/salt_job_factory.rb
  spec/features/bootstrap_cluster_feature_spec.rb
  spec/models/cloud_cluster_spec.rb
  spec/models/salt_handler/cloud_bootstrap_spec.rb
  spec/models/salt_job_spec.rb
  spec/vcr_cassettes/salt/cloud_profile.yml
  spec/vcr_cassettes/salt/login_500.yml
Labels: release-3.0-backport

#525 [3.0] rebase patch
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
Labels: release-3.0-backport

#526 [3.0] Handle kubelet resource reservations
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/velum_general.scss
  app/controllers/internal_api/v1/pillars_controller.rb
  app/controllers/settings/kubelet_compute_resources_reservations_controller.rb
  app/helpers/settings_helper.rb
  app/models/kubelet_compute_resources_reservation.rb
  app/views/layouts/application.html.slim
  app/views/layouts/settings.html.slim
  app/views/settings/_sidebar.html.slim
  app/views/settings/kubelet_compute_resources_reservations/_resources.html.slim
  app/views/settings/kubelet_compute_resources_reservations/index.html.slim
  config/routes.rb
  db/migrate/20180508070232_create_kubelet_compute_resources_reservations.rb
  db/schema.rb
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
  spec/controllers/settings/kubelet_compute_resources_reservations_controller_spec.rb
  spec/factories/kubelet_compute_resources_reservation.rb
  spec/models/kubelet_compute_resources_reservation_spec.rb
Labels: release-3.0-backport

#521 [3.0] Mark admin as updated when we are going to reboot it
  app/controllers/updates_controller.rb
Labels: release-3.0-backport

#527 [3.0][bsc#1087447] validate pillars
  app/controllers/application_controller.rb
  app/models/pillar.rb
Labels: release-3.0-backport

#515 Apply patch
  Gemfile.lock
  packaging/suse/patches/0_change_versions.gem.patch
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
Labels: release-2.1-backport

#523 emphasize settings apply workflow
  app/assets/stylesheets/velum_bootstrap-variables.sass
  app/views/settings/_apply.html.slim
Labels: release-3.0-candidate

#531 [3.0] emphasize settings apply workflow
  app/assets/stylesheets/velum_bootstrap-variables.sass
  app/views/settings/_apply.html.slim
Labels: release-3.0-backport

#534 Redirect to registry page instead of mirror when editing a registry.
  app/views/settings/registries/_form.html.slim
Labels: release-3.0-candidate

#535 Redirect to registry page instead of mirror when editing a registry.
  app/views/settings/registries/_form.html.slim
Labels: release-3.0-backport

#537 Provide UI to manage kubernetes auditing
  app/controllers/settings/auditing_controller.rb
  app/helpers/settings_helper.rb
  app/models/pillar.rb
  app/views/settings/_sidebar.html.slim
  app/views/settings/auditing/index.html.slim
  config/routes.rb
  spec/controllers/settings/auditing_controller_spec.rb
Labels: release-3.0-backport

#540 ui: show kubectl config download link on auth page
  app/helpers/application_helper.rb
  app/views/dashboard/index.html.slim
  app/views/devise/sessions/new.html.slim
  config/routes.rb
Labels: release-3.0-backport

#545 [3.0] Initial implementation of a system wide certificates.
  app/assets/javascripts/settings/index.js
  app/assets/stylesheets/pages/registries.scss
  app/controllers/internal_api/v1/pillars_controller.rb
  app/controllers/settings/base_certificate_controller.rb
  app/controllers/settings/registries_controller.rb
  app/controllers/settings/registry_mirrors_controller.rb
  app/controllers/settings/system_certificates_controller.rb
  app/controllers/setup_controller.rb
  app/helpers/settings_helper.rb
  app/models/system_certificate.rb
  app/views/settings/_sidebar.html.slim
  app/views/settings/registries/_form.html.slim
  app/views/settings/registries/show.html.slim
  app/views/settings/registry_mirrors/_form.html.slim
  app/views/settings/registry_mirrors/show.html.slim
  app/views/settings/system_certificates/_fields.html.slim
  app/views/settings/system_certificates/_form.html.slim
  app/views/settings/system_certificates/edit.html.slim
  app/views/settings/system_certificates/index.html.slim
  app/views/settings/system_certificates/new.html.slim
  app/views/settings/system_certificates/show.html.slim
  app/views/setup/cloud/_settings.html.slim
  app/views/setup/settings/_system_certificate.html.slim
  app/views/setup/welcome.html.slim
  config/routes.rb
  db/migrate/20180517070232_create_system_certificates.rb
  db/schema.rb
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
  spec/controllers/settings/base_certificate_controller_spec.rb
  spec/controllers/settings/registries_controller_spec.rb
  spec/controllers/settings/registry_mirrors_controller_spec.rb
  spec/controllers/settings/system_certificates_controller_spec.rb
  spec/controllers/setup_controller_spec.rb
  spec/factories/system_certificate_factory.rb
  spec/models/system_certificate_spec.rb
Labels: release-3.0-backport

#548 [3.0] ui: fixed unwanted acceptance failure alert
  app/assets/javascripts/dashboard/dashboard.js
Labels: release-3.0-backport

#553 show apply button after each setting creation
  app/views/settings/registries/show.html.slim
  app/views/settings/registry_mirrors/show.html.slim
  app/views/settings/system_certificates/show.html.slim
Labels: release-3.0-candidate

#556 [3.0] show apply button after each setting creation
  app/views/settings/registries/show.html.slim
  app/views/settings/registry_mirrors/show.html.slim
  app/views/settings/system_certificates/show.html.slim
Labels: release-3.0-backport

#552 [3.0] Fix bsc#1091809: add project-id and domain-id fields for openstack
  app/controllers/internal_api/v1/pillars_controller.rb
  app/controllers/setup_controller.rb
  app/models/pillar.rb
  app/views/setup/cloud/_openstack_configuration.html.slim
  lib/tasks/cpi.rake
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
Labels: release-3.0-backport

#546 [2.1] rebase patch
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
Labels: release-2.1-backport

#559 [3.0] ux: toggle domain/project id/name inputs
  app/assets/javascripts/setup/openstack.js
  app/assets/javascripts/setup/setup.js
Labels: release-3.0-backport

#558 Revert "Allow users to choose flannel's backend"
  app/controllers/setup_controller.rb
  app/models/pillar.rb
  app/views/setup/welcome.html.slim
Labels: release-3.0-backport

#562 [3.0] Fix bsc#1062186: update tooltip to explain possible dashboard values.
  app/views/setup/welcome.html.slim
Labels: release-3.0-backport

#563 [2.1] Fix bsc#1062186: update tooltip to explain possible dashboard values.
  app/views/setup/welcome.html.slim
Labels: release-2.1-backport

#565 ui: show proper update failed message and reboot button
  app/assets/javascripts/dashboard/dashboard.js
  app/assets/stylesheets/pages/nodes_list.scss
  app/views/dashboard/index.html.slim
  spec/features/admin_node_update_feature_spec.rb
Labels: bug

#566 [3.0] ui: show proper update failed message and reboot button
  app/assets/javascripts/dashboard/dashboard.js
  app/assets/stylesheets/pages/nodes_list.scss
  app/views/dashboard/index.html.slim
  spec/features/admin_node_update_feature_spec.rb
Labels: release-3.0-backport
