Repository kubic-project/velum, pull requests merged in 2018-04, with the labels that each got.

#490 [2.0] Avoid the event processor from crashing if it cannot interpret the event arguments
  app/models/salt_handler/minion_orchestration.rb
Labels: release-2.0-backport

#489 Avoid the event processor from crashing if it cannot interpret the event arguments
  app/models/salt_handler/orchestration.rb
Labels: release-2.0-candidate

#469 [2.1] Add salt-api timeout
  lib/velum/salt_api.rb
Labels: release-2.1-backport

#467 [2.1] Backport public cloud support to 2.x
  app/assets/javascripts/application.js
  app/assets/javascripts/cloud/bootstrap.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/pages/instance_type.scss
  app/controllers/setup_controller.rb
  app/models/cloud_cluster.rb
  app/models/pillar.rb
  app/views/setup/_cluster_size_panel.html.slim
  app/views/setup/_instance_type_panel.html.slim
  app/views/setup/worker_bootstrap_azure.html.slim
  app/views/setup/worker_bootstrap_ec2.html.slim
  config/data/azure-types.json
  config/data/ec2-types.json
  config/data/gce-types.json
  config/initializers/assets.rb
  config/routes.rb
  lib/tasks/velum.rake
  lib/velum/instance_type.rb
  lib/velum/salt.rb
  spec/controllers/setup_controller_spec.rb
  spec/factories/pillar_factory.rb
  spec/features/bootstrap_in_ec2_feature_spec.rb
  spec/lib/velum/instance_type_spec.rb
  spec/lib/velum/salt_spec.rb
  spec/models/cloud_cluster_spec.rb
  spec/support/helpers.rb
  spec/support/utils.rb
  spec/vcr_cassettes/salt/cloud_profile.yml
  spec/vcr_cassettes/salt/refresh_pillar.yml
  vendor/assets/javascript/bootstrap-slider.min.js
  vendor/assets/stylesheets/bootstrap-slider.min.css
Labels: release-2.1-backport
