Repository kubic-project/velum, pull requests merged in 2018-06, with the labels that each got.

#574 [3.0] ui: do not count failed removal as minion for removal
  app/assets/javascripts/dashboard/dashboard.js
  spec/features/node_force_removal_feature_spec.rb
  spec/features/node_removal_feature_spec.rb
Labels: release-3.0-backport

#573 ui: do not count failed removal as minion for removal
  app/assets/javascripts/dashboard/dashboard.js
  spec/features/node_force_removal_feature_spec.rb
  spec/features/node_removal_feature_spec.rb
Labels: bug

#572 [3.0] ui: added placeholder for mirror registry blank option
  app/views/settings/registry_mirrors/_form.html.slim
Labels: release-3.0-backport

#571 ui: added placeholder for mirror registry blank option
  app/views/settings/registry_mirrors/_form.html.slim
Labels: bug

#578 Backporting eviction hard validation to 3.0
  app/controllers/settings/kubelet_compute_resources_reservations_controller.rb
  app/models/pillar.rb
  app/validators/eviction_validator.rb
  spec/controllers/settings/kubelet_compute_resources_reservations_controller_spec.rb
  spec/models/kubelet_compute_resources_reservation_spec.rb
  spec/models/pillar_spec.rb
Labels: release-3.0-backport

#581 [3.0] Serve the flannel backend on the Pillar API
  app/models/pillar.rb
Labels: P1 Bug, release-3.0-backport

#580 Serve the flannel backend on the Pillar API
  app/models/pillar.rb
Labels: P1 Bug, release-3.0-candidate

#577 BSC#1093565: Dynamically adjust cluster growth based on existing cluster size
  app/controllers/setup_controller.rb
  app/decorators/cluster_size_slider_decorator.rb
  app/models/cloud_cluster.rb
  app/views/setup/_cluster_size_panel.html.slim
  spec/features/bootstrap_in_ec2_feature_spec.rb
  spec/models/cloud_cluster_spec.rb
  vendor/assets/javascript/bootstrap-slider.min.js
  vendor/assets/stylesheets/bootstrap-slider.min.css
Labels: release-2.1-backport

#576 BSC#1093565: Dynamically adjust cluster growth based on existing cluster size
  app/controllers/setup_controller.rb
  app/decorators/cluster_size_slider_decorator.rb
  app/models/cloud_cluster.rb
  app/views/setup/_cluster_size_panel.html.slim
  spec/features/bootstrap_in_ec2_feature_spec.rb
  spec/models/cloud_cluster_spec.rb
  vendor/assets/javascript/bootstrap-slider.min.js
  vendor/assets/stylesheets/bootstrap-slider.min.css
Labels: release-3.0-backport

#591 update sprockets to fix cve-2018-3760 cve#2018-3760
  Gemfile.lock
Labels: release-3.0-candidate
