Repository kubic-project/velum, pull requests merged in 2018-08, with the labels that each got.

#619 fix tests that were broken because PR#595 wasn't rebased before mergi…
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
Labels: release-3.0-candidate

#610 [bsc#1098085] keep information about adding nodes to the cluster
  app/controllers/setup_controller.rb
  app/views/dashboard/index.html.slim
  app/views/setup/worker_bootstrap.html.slim
Labels: P2 bug, bug, release-3.0-candidate

#606 [3.0] bsc1097754: certificate verification
  app/models/certificate.rb
  app/validators/x509_certificate_validator.rb
  spec/controllers/internal_api/v1/pillars_controller_spec.rb
  spec/controllers/settings/registries_controller_spec.rb
  spec/controllers/settings/registry_mirrors_controller_spec.rb
  spec/controllers/settings/system_certificates_controller_spec.rb
  spec/controllers/setup_controller_spec.rb
  spec/factories/certificate_factory.rb
  spec/features/settings/mirrors_feature_spec.rb
  spec/features/settings/registries_feature_spec.rb
  spec/models/certificate_spec.rb
  spec/rails_helper.rb
Labels: release-3.0-backport

#603 [3.0] save online status through reconciler (bsc#1098436)
  app/assets/javascripts/dashboard/dashboard.js
  app/models/minion.rb
  app/views/dashboard/index.html.slim
  bin/init
  db/migrate/20181708070233_add_online_status_to_minions.rb
  db/schema.rb
  packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
  spec/features/monitoring_feature_spec.rb
Labels: release-3.0-backport

#622 [3.0][bsc#1098085] keep information about adding nodes to the cluster
  app/controllers/setup_controller.rb
  app/views/dashboard/index.html.slim
  app/views/setup/worker_bootstrap.html.slim
Labels: P2 bug, bug, release-3.0-backport

#614 Update the minion hostname in a regular basis, based on the grain information.
  app/models/minion.rb
Labels: release-3.0-candidate

#608 [bsc#1099015] when rebooting admin, set tx_update_reboot_needed to false
  app/controllers/updates_controller.rb
Labels: P2 bug, bug, release-3.0-candidate
